# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 01:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0002_candidaterelease_spotify_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_end_date', models.DateField(default=datetime.datetime(2016, 8, 19, 20, 3, 20, 796479))),
            ],
        ),
    ]
