# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 01:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0003_weeklycandidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklycandidates',
            name='week_end_date',
        ),
        migrations.AddField(
            model_name='weeklycandidates',
            name='week_date',
            field=models.DateField(default=datetime.datetime(2016, 8, 19, 20, 21, 12, 640891)),
        ),
    ]
