# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0004_auto_20160819_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterelease',
            name='sorting_hat_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='sorting_hat_track_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklycandidates',
            name='week_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
