# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0005_auto_20160819_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyCandidates',
            new_name='CandidateSet',
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='week',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.CandidateSet'),
            preserve_default=False,
        ),
    ]
