# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0007_auto_20160820_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterelease',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
