# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0008_auto_20160826_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterelease',
            name='eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='image_300',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='image_64',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='image_640',
            field=models.URLField(null=True),
        ),
    ]
