# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0009_auto_20160827_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='genres',
            field=models.ManyToManyField(to='sausage_grinder.Genre'),
        ),
    ]
