# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0010_auto_20160829_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateArtist',
            fields=[
                ('spotify_uri', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateTrack',
            fields=[
                ('spotify_uri', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('track_number', models.IntegerField(default=0)),
                ('disc_number', models.IntegerField(default=0)),
                ('artists', models.ManyToManyField(to='sausage_grinder.CandidateArtist')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.CandidateRelease')),
            ],
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='artists',
            field=models.ManyToManyField(to='sausage_grinder.CandidateArtist'),
        ),
    ]
