# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0011_auto_20160830_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateArtistRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('FEATURED', 'FEATURED')], default='PRIMARY', max_length=8)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.CandidateArtist')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidatetrack',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='candidaterelease',
            name='artists',
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='artists',
            field=models.ManyToManyField(through='sausage_grinder.CandidateArtistRelease', to='sausage_grinder.CandidateArtist'),
        ),
        migrations.AddField(
            model_name='candidateartistrelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.CandidateRelease'),
        ),
    ]
