# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0012_auto_20160831_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateartist',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
