# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0013_candidateartist_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateartist',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateartist',
            name='genres',
            field=models.ManyToManyField(to='sausage_grinder.Genre'),
        ),
        migrations.AddField(
            model_name='candidateartist',
            name='image_300',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='candidateartist',
            name='image_600',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='candidateartist',
            name='image_64',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='candidateartist',
            name='image_640',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='candidateartist',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='image_600',
            field=models.URLField(null=True),
        ),
    ]
