# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0014_auto_20160908_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetrack',
            name='single_release_date',
            field=models.DateField(null=True),
        ),
    ]
