# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0015_candidatetrack_single_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterelease',
            name='artist_popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidaterelease',
            name='popularity_class',
            field=models.CharField(choices=[('top', 'Top 50'), ('verge', 'On the Verge'), ('unheralded', 'Unheralded'), ('underground', 'Underground'), ('unknown', 'Unknown')], default='', max_length=255),
        ),
    ]
