# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0017_auto_20160910_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterelease',
            name='has_single',
            field=models.BooleanField(default=False),
        ),
    ]
