# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0019_auto_20160927_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_hat_track_num', models.IntegerField(default=0)),
                ('sorting_hat_rank', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('artist_popularity', models.IntegerField(default=0)),
                ('popularity_class', models.CharField(choices=[('top', 'Top 50'), ('verge', 'On the Verge'), ('unheralded', 'Unheralded'), ('underground', 'Underground'), ('unknown', 'Unknown')], default='', max_length=255)),
                ('eligible', models.BooleanField(default=True)),
                ('processed', models.BooleanField(default=False)),
                ('has_single', models.BooleanField(default=False)),
                ('spotify_uri', models.CharField(default='', max_length=255)),
                ('batch', models.IntegerField(default=0)),
                ('release_date', models.DateField(null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('image_640', models.URLField(null=True)),
                ('image_600', models.URLField(null=True)),
                ('image_300', models.URLField(null=True)),
                ('image_64', models.URLField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CandidateArtist',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='CandidateArtistRelease',
            new_name='ArtistRelease',
        ),
        migrations.RenameModel(
            old_name='CandidateSet',
            new_name='ReleaseSet',
        ),
        migrations.RenameModel(
            old_name='CandidateTrack',
            new_name='Track',
        ),
        migrations.RemoveField(
            model_name='candidaterelease',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='candidaterelease',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='candidaterelease',
            name='week',
        ),
        migrations.AlterField(
            model_name='artistrelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.Release'),
        ),
        migrations.AlterField(
            model_name='track',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.Release'),
        ),
        migrations.DeleteModel(
            name='CandidateRelease',
        ),
        migrations.AddField(
            model_name='release',
            name='artists',
            field=models.ManyToManyField(through='sausage_grinder.ArtistRelease', to='sausage_grinder.Artist'),
        ),
        migrations.AddField(
            model_name='release',
            name='genres',
            field=models.ManyToManyField(to='sausage_grinder.Genre'),
        ),
        migrations.AddField(
            model_name='release',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.ReleaseSet'),
        ),
    ]
