# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0020_auto_20161018_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='is_freshcut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='is_sapling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='is_freshcut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='is_sapling',
            field=models.BooleanField(default=False),
        ),
    ]
