# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0021_auto_20161018_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('JJE', 'Jesse'), ('JT', 'Moksha'), ('AG', 'Adam'), ('MC', 'Meta Critic'), ('SP', 'Spotify'), ('AM', 'All Music'), ('QOS', 'Consequence of Sound')], max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='release',
            old_name='is_sapling',
            new_name='is_sample',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='is_sapling',
            new_name='is_sample',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.Release'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.ReleaseSet'),
        ),
    ]
