# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0022_auto_20161026_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='week',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='type',
            field=models.CharField(choices=[('Jesse', 'Jesse'), ('Moksha', 'Moksha'), ('Adam', 'Adam'), ('Audio Bonsai', 'Audio Bonsai'), ('MC', 'Meta Critic'), ('SP', 'Spotify'), ('AM', 'All Music'), ('QOS', 'Consequence of Sound')], max_length=25),
        ),
    ]
