# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0023_auto_20161028_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='track',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.Track'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='week',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sausage_grinder.ReleaseSet'),
            preserve_default=False,
        ),
    ]
