# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0025_remove_recommendation_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseset',
            name='sampler_uri',
            field=models.CharField(default='', max_length=255),
        ),
    ]
