# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0026_releaseset_sampler_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='week',
        ),
    ]
