# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0028_remove_artist_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseset',
            name='sampler_uri',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
