# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0029_auto_20161028_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='max_foll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='max_pop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='release_day_foll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='release_day_pop',
            field=models.IntegerField(default=0),
        ),
    ]
