# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0029_auto_20161028_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseset',
            name='adam_vote_uri',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='releaseset',
            name='jesse_vote_uri',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='releaseset',
            name='moksha_vote_uri',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
