# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0030_auto_20170102_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='genres',
            field=models.ManyToManyField(blank=True, to='sausage_grinder.Genre'),
        ),
        migrations.AlterField(
            model_name='release',
            name='image_300',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='image_600',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='image_64',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='image_640',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
