# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0031_auto_20170109_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
