# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0032_recommendation_position'),
        ('sausage_grinder', '0030_auto_20170822_2214'),
    ]

    operations = [
    ]
