# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0034_auto_20171013_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='weeks',
            field=models.ManyToManyField(to='sausage_grinder.ReleaseSet'),
        ),
    ]
