# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sausage_grinder', '0036_release_release_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('single', 'Single'), ('ep', 'EP'), ('album', 'Album')], default='', max_length=255),
        ),
    ]
